/**
 * Home Assistant automation generator.
 *
 * Generates a YAML automation file that can be imported into Home Assistant
 * to trigger Plex playback of a specific movie, TV show, or episode.
 */

import inquirer from 'inquirer';
import * as fs from 'fs';
import * as path from 'path';
import chalk from 'chalk';
import { printError, printSuccess, printInfo, printHeader, fmtItemLabel } from '../display';
import type { PlexClient } from '../api';
import type { PlexItem } from '../types';

// ---------------------------------------------------------------------------
// Helpers (exported for testing)
// ---------------------------------------------------------------------------

/** Sanitise text into a safe HA entity_id slug. */
export function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .substring(0, 60);
}

/** Map a PlexItem type to the HA media_content_type expected by Plex integration. */
export function haMediaType(item: PlexItem): string {
  const map: Record<string, string> = {
    movie: 'movie',
    show: 'tvshow',
    season: 'season',
    episode: 'episode',
    track: 'music',
    album: 'album',
    artist: 'artist',
  };
  return map[item.type ?? ''] ?? 'video';
}

/**
 * Build the `media_content_id` JSON string understood by the Plex HA integration.
 * See https://www.home-assistant.io/integrations/plex/
 */
export function buildContentId(item: PlexItem, libraryName: string, resume: boolean): string {
  const type = item.type ?? '';

  if (type === 'movie') {
    return JSON.stringify({ library_name: libraryName, title: item.title });
  }

  if (type === 'show') {
    if (resume) {
      return JSON.stringify({ library_name: libraryName, show: item.title, resume: true });
    }
    // Start from S01E01
    return JSON.stringify({
      library_name: libraryName,
      show: item.title,
      season: 1,
      episode: 1,
    });
  }

  if (type === 'episode') {
    const obj: Record<string, unknown> = {
      library_name: libraryName,
      show: item.grandparentTitle ?? item.title,
    };
    if (item.parentIndex != null) obj.season = item.parentIndex;
    if (item.index != null) obj.episode = item.index;
    return JSON.stringify(obj);
  }

  // Generic fallback
  return JSON.stringify({ library_name: libraryName, title: item.title });
}

/** Render the full Home Assistant automation YAML string. */
export function renderYaml(params: {
  alias: string;
  description: string;
  inputButtonSlug: string;
  mediaPlayerEntity: string;
  mediaContentType: string;
  mediaContentId: string;
}): string {
  const {
    alias,
    description,
    inputButtonSlug,
    mediaPlayerEntity,
    mediaContentType,
    mediaContentId,
  } = params;

  const escapedAlias = alias.replace(/"/g, '\\"');
  const escapedDesc = description.replace(/"/g, '\\"');

  return [
    `# Home Assistant Automation — generated by plex-cli`,
    `# -----------------------------------------------------------------`,
    `# SETUP STEPS:`,
    `# 1. Create a Button helper in HA:`,
    `#      Settings → Devices & Services → Helpers → + Create Helper → Button`,
    `#      Name:      ${alias}`,
    `#      Entity ID: input_button.${inputButtonSlug}`,
    `# 2. Import this automation:`,
    `#      Settings → Automations & Scenes → + Add Automation → Edit as YAML`,
    `#      (or append to automations.yaml and reload HA).`,
    `# 3. Update "entity_id" below to match your actual Plex media player entity.`,
    `# -----------------------------------------------------------------`,
    ``,
    `alias: "${escapedAlias}"`,
    `description: "${escapedDesc}"`,
    `mode: single`,
    ``,
    `triggers:`,
    `  - trigger: state`,
    `    entity_id: input_button.${inputButtonSlug}`,
    `    to: ~`,
    ``,
    `actions:`,
    `  - action: media_player.play_media`,
    `    target:`,
    `      entity_id: ${mediaPlayerEntity}`,
    `    data:`,
    `      media_content_type: "${mediaContentType}"`,
    `      media_content_id: >-`,
    `        ${mediaContentId}`,
    ``,
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Interactive menu
// ---------------------------------------------------------------------------

export async function runHassMenu(client: PlexClient): Promise<void> {
  printHeader('Generate Home Assistant Automation');
  printInfo(
    'Generates a YAML automation file to trigger Plex playback from Home Assistant.\n'
  );

  // 1. Search for the title
  const { query } = await inquirer.prompt<{ query: string }>([
    { type: 'input', name: 'query', message: 'Search for a title (blank to cancel):' },
  ]);
  if (!query.trim()) return;

  let results: PlexItem[];
  try {
    results = await client.search(query.trim());
  } catch (err: unknown) {
    printError((err as Error).message);
    return;
  }

  if (!results.length) {
    printInfo('No results found.');
    return;
  }

  const { chosen } = await inquirer.prompt<{ chosen: PlexItem | null }>([
    {
      type: 'list',
      name: 'chosen',
      message: 'Select an item:',
      choices: [
        ...results.map((r) => ({
          name: `${fmtItemLabel(r)} (${r.type ?? '?'}${r.year ? ', ' + r.year : ''})`,
          value: r,
        })),
        { name: '← Cancel', value: null },
      ],
    },
  ]);
  if (!chosen) return;

  // 2. Fetch full metadata for librarySectionTitle + episode index fields
  let full: PlexItem = chosen;
  if (chosen.ratingKey) {
    try {
      full = await client.metadata(chosen.ratingKey);
    } catch {
      // fall back to search result
    }
  }

  const libraryName = full.librarySectionTitle ?? 'your_library_name';

  // 3. Warn if library name is unknown
  if (libraryName === 'your_library_name') {
    printInfo(
      chalk.yellow('⚠  Could not determine library name — you will need to edit the YAML manually.')
    );
  }

  // 4. Resume option for TV shows
  let resume = false;
  if (full.type === 'show') {
    const { doResume } = await inquirer.prompt<{ doResume: boolean }>([
      {
        type: 'confirm',
        name: 'doResume',
        message: 'Resume the show from where you left off (On Deck)?',
        default: true,
      },
    ]);
    resume = doResume;
  }

  // 5. HA media_player entity
  const { mediaPlayerEntity } = await inquirer.prompt<{ mediaPlayerEntity: string }>([
    {
      type: 'input',
      name: 'mediaPlayerEntity',
      message: 'Home Assistant media_player entity ID:',
      default: 'media_player.plex_player',
    },
  ]);

  // 6. Automation alias
  const label = fmtItemLabel(full);
  const defaultAlias = resume ? `Resume ${label} on Plex` : `Play ${label} on Plex`;
  const { alias } = await inquirer.prompt<{ alias: string }>([
    {
      type: 'input',
      name: 'alias',
      message: 'Automation name / alias:',
      default: defaultAlias,
    },
  ]);

  // 7. Output path
  const defaultOutput = path.join('homeassistant', `${slugify(alias)}.yaml`);
  const { outputPath } = await inquirer.prompt<{ outputPath: string }>([
    {
      type: 'input',
      name: 'outputPath',
      message: 'Output file path:',
      default: defaultOutput,
    },
  ]);

  // 8. Generate and write
  const contentId = buildContentId(full, libraryName, resume);
  const inputButtonSlug = slugify(alias);
  const yaml = renderYaml({
    alias,
    description: `Automation generated by plex-cli for ${label}`,
    inputButtonSlug,
    mediaPlayerEntity: mediaPlayerEntity || 'media_player.plex_player',
    mediaContentType: haMediaType(full),
    mediaContentId: contentId,
  });

  const resolvedPath = path.resolve(outputPath);
  try {
    const dir = path.dirname(resolvedPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(resolvedPath, yaml, 'utf-8');
    printSuccess(`Automation saved → ${resolvedPath}`);
    console.log(chalk.dim('\nPreview:'));
    console.log(chalk.cyan('─'.repeat(60)));
    console.log(yaml);
    console.log(chalk.cyan('─'.repeat(60)));
  } catch (err: unknown) {
    printError(`Failed to write file: ${(err as Error).message}`);
  }
}

// ---------------------------------------------------------------------------
// Non-interactive helper (used by the CLI sub-command)
// ---------------------------------------------------------------------------

export async function generateHassAutomation(
  client: PlexClient,
  query: string,
  opts: {
    player?: string;
    output?: string;
    resume?: boolean;
    type?: string;
  }
): Promise<void> {
  let results: PlexItem[];
  try {
    results = await client.search(query, 10);
  } catch (err: unknown) {
    printError((err as Error).message);
    process.exit(1);
  }

  if (!results.length) {
    printError(`No results found for "${query}".`);
    process.exit(1);
  }

  // Pick best match: prefer exact title match, otherwise first result
  const typeFilter = opts.type;
  const filtered = typeFilter ? results.filter((r) => r.type === typeFilter) : results;
  const item = filtered[0] ?? results[0];

  // Fetch full metadata
  let full: PlexItem = item;
  if (item.ratingKey) {
    try {
      full = await client.metadata(item.ratingKey);
    } catch { /* fall back */ }
  }

  const libraryName = full.librarySectionTitle ?? 'your_library_name';
  const resume = opts.resume ?? full.type === 'show';
  const label = fmtItemLabel(full);
  const alias = resume ? `Resume ${label} on Plex` : `Play ${label} on Plex`;
  const mediaPlayerEntity = opts.player ?? 'media_player.plex_player';
  const outputPath = opts.output ?? path.join('homeassistant', `${slugify(alias)}.yaml`);

  const contentId = buildContentId(full, libraryName, resume);
  const inputButtonSlug = slugify(alias);
  const yaml = renderYaml({
    alias,
    description: `Automation generated by plex-cli for ${label}`,
    inputButtonSlug,
    mediaPlayerEntity,
    mediaContentType: haMediaType(full),
    mediaContentId: contentId,
  });

  const resolvedPath = path.resolve(outputPath);
  const dir = path.dirname(resolvedPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(resolvedPath, yaml, 'utf-8');
  printSuccess(`Automation saved → ${resolvedPath}`);
  console.log(yaml);
}
